<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class GameSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \App\Models\Game::truncate();

        $games = [
            // Puzzle Games (5)
            [
                'title' => 'Treasure Hunt Decoder',
                'slug' => 'treasure-hunt-decoder',
                'description' => 'Solve riddles & unlock hidden treasures step by step.',
                'levels' => 40,
                'difficulty' => 'easy',
                'category' => 'puzzle',
                'color' => '#FF6B6B',
                'icon' => null,
                'image' => '/images/027b84fad71d408eb0a234f9c2f7f654.jpg',
                'is_active' => true,
            ],
            [
                'title' => 'Shape Swapper Quest',
                'slug' => 'shape-swapper-quest',
                'description' => 'Match shapes, slide them into place, complete the picture.',
                'levels' => 40,
                'difficulty' => 'medium',
                'category' => 'puzzle',
                'color' => '#4ECDC4',
                'icon' => null,
                'image' => '/images/1cea69166c244bd899decd2488509d4c.jpg',
                'is_active' => true,
            ],
            [
                'title' => 'Pattern Builder Pro',
                'slug' => 'pattern-builder-pro',
                'description' => 'Complete patterns, spot the missing piece, keep the sequence flowing.',
                'levels' => 40,
                'difficulty' => 'medium',
                'category' => 'puzzle',
                'color' => '#95E1D3',
                'icon' => null,
                'image' => '/images/2d29cc9fc14a4bd5911bcab8a2a9cf06.jpg',
                'is_active' => true,
            ],
            [
                'title' => 'Tile Tumbler Master',
                'slug' => 'tile-tumbler-master',
                'description' => 'Flip & match tiles, train memory & spot-the-difference skills.',
                'levels' => 40,
                'difficulty' => 'easy',
                'category' => 'puzzle',
                'color' => '#FFA07A',
                'icon' => null,
                'image' => '/images/355b7e3d99ea47d39e376d445b90c037.jpg',
                'is_active' => true,
            ],
            [
                'title' => 'Lost Items Finder',
                'slug' => 'lost-items-finder',
                'description' => 'Find missing objects in busy scenes, observation challenge.',
                'levels' => 40,
                'difficulty' => 'medium',
                'category' => 'puzzle',
                'color' => '#F38181',
                'icon' => null,
                'image' => '/images/40d739d6f93f43eb9efeef152d4efa05.jpg',
                'is_active' => true,
            ],

            // Coloring Games (5)
            [
                'title' => 'Rainbow Art Studio',
                'slug' => 'rainbow-art-studio',
                'description' => 'Paint & color amazing creatures, unlock new color palettes.',
                'levels' => 40,
                'difficulty' => 'easy',
                'category' => 'coloring',
                'color' => '#FFD93D',
                'icon' => null,
                'image' => '/images/42675aa0355d4e90bf895483ba41c149.jpg',
                'is_active' => true,
            ],
            [
                'title' => 'Splash Paint Adventure',
                'slug' => 'splash-paint-adventure',
                'description' => 'Drag colors, splash & blend, create beautiful artwork.',
                'levels' => 40,
                'difficulty' => 'easy',
                'category' => 'coloring',
                'color' => '#6BCB77',
                'icon' => null,
                'image' => '/images/4553f4347c2246ec8ba67481c1fbaedb.jpg',
                'is_active' => true,
            ],
            [
                'title' => 'Magic Color Quiz',
                'slug' => 'magic-color-quiz',
                'description' => 'Answer color questions, mix pigments, create new shades.',
                'levels' => 40,
                'difficulty' => 'easy',
                'category' => 'coloring',
                'color' => '#FFD60A',
                'icon' => null,
                'image' => '/images/514ac8d0a601421e8a28bc2ec18f64de.jpg',
                'is_active' => true,
            ],
            [
                'title' => 'Pigment Palace',
                'slug' => 'pigment-palace',
                'description' => 'Design & color fantasy rooms, unlock accessories.',
                'levels' => 40,
                'difficulty' => 'medium',
                'category' => 'coloring',
                'color' => '#9D84B7',
                'icon' => null,
                'image' => '/images/5cad7468048945b2a0cd32ac22f413b2.jpg',
                'is_active' => true,
            ],
            [
                'title' => 'Brushstroke Blends',
                'slug' => 'brushstroke-blends',
                'description' => 'Layer colors, blend smoothly, master the art of painting.',
                'levels' => 40,
                'difficulty' => 'medium',
                'category' => 'coloring',
                'color' => '#FFB703',
                'icon' => null,
                'image' => '/images/6af6bcf3424a4a0b9a5b93346ebe88bc.jpg',
                'is_active' => true,
            ],

            // Brain Games (4)
            [
                'title' => 'Riddle Racers',
                'slug' => 'riddle-racers',
                'description' => 'Quick funny riddles, silly answers, laugh & learn challenges.',
                'levels' => 40,
                'difficulty' => 'easy',
                'category' => 'brain',
                'color' => '#EE5A24',
                'icon' => null,
                'image' => '/images/6c2add4dc9054ef783d30d16cd56c336.jpg',
                'is_active' => true,
            ],
            [
                'title' => 'What If Wonderland',
                'slug' => 'what-if-wonderland',
                'description' => 'Imagine wild scenarios, make silly decisions, explore imagination.',
                'levels' => 40,
                'difficulty' => 'easy',
                'category' => 'brain',
                'color' => '#F97316',
                'icon' => null,
                'image' => '/images/6d28b465fd1440aa996c7b4c03d55b25.jpg',
                'is_active' => true,
            ],
            [
                'title' => 'Silly Stories Spinner',
                'slug' => 'silly-stories-spinner',
                'description' => 'Build weird tales, mix characters & adventures together.',
                'levels' => 40,
                'difficulty' => 'medium',
                'category' => 'brain',
                'color' => '#EC4899',
                'icon' => null,
                'image' => '/images/6e8212d4e6f54070b7331bf5eccbad74.jpg',
                'is_active' => true,
            ],
            [
                'title' => 'Think Fast Challenge',
                'slug' => 'think-fast-challenge',
                'description' => 'Quick questions, snap decisions, test your quick thinking.',
                'levels' => 40,
                'difficulty' => 'hard',
                'category' => 'brain',
                'color' => '#8B5CF6',
                'icon' => null,
                'image' => '/images/7bf7ab72e8214685baa6707cdbd7142d.png',
                'is_active' => true,
            ],

            // Memory Games (4)
            [
                'title' => 'Memory Mansion',
                'slug' => 'memory-mansion',
                'description' => 'Peek at rooms, remember furniture, spot what moved.',
                'levels' => 40,
                'difficulty' => 'medium',
                'category' => 'memory',
                'color' => '#06B6D4',
                'icon' => null,
                'image' => '/images/8bc0900d81fe449690b88a12f31b9cf6.jpg',
                'is_active' => true,
            ],
            [
                'title' => 'Sequence Snapshot',
                'slug' => 'sequence-snapshot',
                'description' => 'Watch sequences flash, remember the order, tap them back.',
                'levels' => 40,
                'difficulty' => 'medium',
                'category' => 'memory',
                'color' => '#10B981',
                'icon' => null,
                'image' => '/images/998baa345845479abda3fbf45d29e48f.gif',
                'is_active' => true,
            ],
            [
                'title' => 'Picture Perfect Pairs',
                'slug' => 'picture-perfect-pairs',
                'description' => 'Match identical pictures, train focus & recognition skills.',
                'levels' => 40,
                'difficulty' => 'easy',
                'category' => 'memory',
                'color' => '#F43F5E',
                'icon' => null,
                'image' => '/images/a3c687ded3f14e45b94631c0dfd8c6c8.jpg',
                'is_active' => true,
            ],
            [
                'title' => 'Watch & Recall',
                'slug' => 'watch-and-recall',
                'description' => 'Observe carefully, cover up, recall what you saw.',
                'levels' => 40,
                'difficulty' => 'medium',
                'category' => 'memory',
                'color' => '#7C3AED',
                'icon' => null,
                'image' => '/images/bb30a208eda647b3a8026d5ef18eca78.png',
                'is_active' => true,
            ],

            // Logic & Math Games (4)
            [
                'title' => 'Number Ninja',
                'slug' => 'number-ninja',
                'description' => 'Simple additions, subtractions, counting in fun ways.',
                'levels' => 40,
                'difficulty' => 'easy',
                'category' => 'logic',
                'color' => '#14B8A6',
                'icon' => null,
                'image' => '/images/c6289d78da9e4e388979eed008326da7.jpg',
                'is_active' => true,
            ],
            [
                'title' => 'Pattern Prophecy',
                'slug' => 'pattern-prophecy',
                'description' => 'Spot patterns, predict sequences, grow number sense.',
                'levels' => 40,
                'difficulty' => 'medium',
                'category' => 'logic',
                'color' => '#D946EF',
                'icon' => null,
                'image' => '/images/cce333d2755645d8a70bd2492c008843.jpg',
                'is_active' => true,
            ],
            [
                'title' => 'True or False Factory',
                'slug' => 'true-or-false-factory',
                'description' => 'Decide if statements are right or wrong, test logic skills.',
                'levels' => 40,
                'difficulty' => 'medium',
                'category' => 'logic',
                'color' => '#F59E0B',
                'icon' => null,
                'image' => '/images/e0639629f2b54d6c886d216b6cac4bbb.jpg',
                'is_active' => true,
            ],
            [
                'title' => 'Sort & Stack Strategy',
                'slug' => 'sort-and-stack-strategy',
                'description' => 'Sort objects by size, color, or type, organize & match.',
                'levels' => 40,
                'difficulty' => 'hard',
                'category' => 'logic',
                'color' => '#6366F1',
                'icon' => null,
                'image' => '/images/f7f0049ef49b40f286b11ddb6a430ed7.jpg',
                'is_active' => true,
            ],
        ];

        foreach ($games as $game) {
            \App\Models\Game::create($game);
        }
    }
}
